version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase-{{USERNAME}}
    restart: always
    volumes:
      - metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db
      JAVA_OPTS: -Xmx1g
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metabase-{{USERNAME}}.rule=Host(`{{SUBDOMAIN}}`)"
      - "traefik.http.routers.metabase-{{USERNAME}}.entrypoints=http,https"
      - "traefik.http.routers.metabase-{{USERNAME}}.tls=true"
      - "traefik.http.routers.metabase-{{USERNAME}}.tls.certresolver=letsencrypt"
      - "traefik.http.services.metabase-{{USERNAME}}.loadbalancer.server.port=3000"
    networks:
      - coolify
      - traefik-network

volumes:
  metabase-data:
    name: metabase-data-{{USERNAME}}

networks:
  coolify:
    external: true
  traefik-network:
    external: true
