version: 2

models:
  - name: example_model
    description: "A simple example model for Lightdash demo"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: name
        description: "Name field"
      - name: created_at
        description: "Timestamp when the record was created"
